@startuml
  participant Backend
  participant BookingService
  participant User
  participant CarOrHotel

  group 200 OK
    Backend -> BookingService : passing context payload
      activate BookingService
    BookingService -> User : instantiates Booking object
      activate User
    User -> User : check User business rules
    User -> CarOrHotel : checks Asset to book
      activate CarOrHotel
    CarOrHotel -> CarOrHotel  : checks status
    CarOrHotel -> CarOrHotel  : checks availability
    
    CarOrHotel --> User : returns available Asset
      deactivate CarOrHotel
    User --> BookingService : returns successful Booking simulation
      deactivate User
    BookingService --> BookingService : process pricing
    BookingService --> Backend : location, pricing payload
      deactivate BookingService
  end

  group 300-500 ERROR
    Backend -> BookingService : passing context payload
      activate BookingService
    
    BookingService -> User : instantiates Booking object
      activate User
    User -[#red]-> User : check User business rules
    User -[#red]-> BookingService : User business rules ERROR
    BookingService -[#red]-> Backend : User business rules ERROR

    User -> CarOrHotel : checks Asset to book
      activate CarOrHotel
    CarOrHotel -> CarOrHotel  : checks status
    CarOrHotel -> CarOrHotel  : checks availability
    CarOrHotel -[#red]-> User : Asset booking ERROR
      deactivate CarOrHotel
    User -[#red]-> BookingService : Asset booking ERROR
      deactivate User
    BookingService -[#red]-> Backend : Asset booking ERROR
      deactivate BookingService
  end
@enduml